### ISSUE TITLE
PHP error 7.2

### ISSUE THREAD

**Issue by opicron** [onedesigns/one-user-avatar#1]
When moving from ProfilePress (previous WP User Avatar) I got a critical error on the site. The following error was filling up the logs on PHP 7.2

`Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp-content/plugins/one-user-avatar/includes/class-wp-user-avatar-functions.php on line 564`

It can be fixed by removing the comma on line 563, like so:

`esc_attr( $size )`

Would you be so kind to update the plugin? Thanks!

**Comment by onedesigns** [comment]
Thanks. I have fixed it in [version 2.3.3](https://github.com/onedesigns/one-user-avatar/releases/tag/2.3.3)

**Comment by w3guy** [comment]
@onedesigns I sent an email via your website contact form. Please respond as soon as you can.

**Comment by w3guy** [comment]
@onedesigns I sent an email via your website contact form. Please respond as soon as you can. 

Please 🙏🙏🙏

**Comment by w3guy** [comment]
@onedesigns how do I reach you, please?
